export const ships = [
  { id: 'hms-nelson', name: 'HMS Nelson', nation: 'HMS', class: 'Nelson', type: 'Battleship', hints: ['Kolme päätykkitornia on ryhmitetty kokonaan komentosillan etupuolelle.', 'Jokaisessa päätykkitornissa on kolme putkea: 3 + 3 + 3.', 'Etsi yksi savupiippu lyhyen ja tiiviin ylärakenteen takaa.'], silhouette: 'Ships/HMS/Nelson/HMS%20Nelson/Silhouette.jpg' },
  { id: 'hms-hood', name: 'HMS Hood', nation: 'HMS', class: 'Admiral', type: 'Battlecruiser', hints: ['Neljä kaksoistykkitornia jakautuu tasan: kaksi keulassa ja kaksi perässä.', 'Etsi kaksi näkyvää, lähellä toisiaan olevaa savupiippua keskilaivasta.', 'Pitkä ja matala runko saa aluksen näyttämään kokoonsa nähden hoikalta.'], silhouette: 'Ships/HMS/Admiral/HMS%20Hood/Silhouette.jpg' },
  { id: 'hms-king-george-v', name: 'HMS King George V', nation: 'HMS', class: 'King George V', type: 'Battleship', hints: ['Pääaseistus muodostuu kahdesta hyvin leveästä ja yhdestä kapeammasta tykkitornista.', 'Laske putket: 4 + 4 + 2; kaksi tornia keulassa ja yksi perässä.', 'Porrastettu etuylärakenne nousee heti keulan tykkitornien takaa.'], silhouette: 'Ships/HMS/King%20George%20V/HMS%20King%20George%20V/Silhouette.jpg' },
  { id: 'hms-prince-of-wales', name: 'HMS Prince of Wales', nation: 'HMS', class: 'King George V', type: 'Battleship', hints: ['Pääaseistus muodostuu kahdesta hyvin leveästä ja yhdestä kapeammasta tykkitornista.', 'Laske putket: 4 + 4 + 2; kaksi tornia keulassa ja yksi perässä.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama tykkijärjestely.'], silhouette: 'Ships/HMS/King%20George%20V/HMS%20Prince%20of%20Wales/Silhouette.jpg' },
  { id: 'hms-belfast', name: 'HMS Belfast', nation: 'HMS', class: 'Town', type: 'Light Cruiser', hints: ['Neljä kompaktia kolmoistykkitornia muodostaa parit keulaan ja perään.', 'Etsi kaksi hoikkaa, keskilaivan tuntumaan ryhmitettyä savupiippua.', 'Runko ja tykkitornit ovat selvästi kevyemmät ja pienemmät kuin taistelulaivassa.'], silhouette: 'Ships/HMS/Town/HMS%20Belfast/Silhouette.jpg' },
  { id: 'kms-bismarck', name: 'Bismarck', nation: 'KMS', class: 'Bismarck', type: 'Battleship', hints: ['Neljä kaksoistykkitornia on sijoitettu pareittain keulaan ja perään.', 'Yksi leveä savupiippu on korkean, porrastetun etutornin takana.', 'Korkea etuylärakenne on parempi tunnistuspiste kuin pelkkä tykkijärjestely.'], silhouette: 'Ships/KMS/Bismarck/Bismarck/Silhouette.jpg' },
  { id: 'kms-tirpitz', name: 'Tirpitz', nation: 'KMS', class: 'Bismarck', type: 'Battleship', hints: ['Neljä kaksoistykkitornia on sijoitettu pareittain keulaan ja perään.', 'Yksi leveä savupiippu on korkean, porrastetun etutornin takana.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama perusjärjestely.'], silhouette: 'Ships/KMS/Bismarck/Tirpitz/Silhouette.jpg' },
  { id: 'kms-scharnhorst', name: 'Scharnhorst', nation: 'KMS', class: 'Scharnhorst', type: 'Battleship', hints: ['Kolme kolmoistykkitornia muodostaa 2-keulassa, 1-perässä -järjestelyn.', 'Torneissa on yhteensä 3 + 3 + 3 putkea, ei neliputkisia torneja.', 'Etsi yksi leveä savupiippu ja verrattain virtaviivainen etutorni.'], silhouette: 'Ships/KMS/Scharnhorst/Scharnhorst/Silhouette.jpg' },
  { id: 'kms-prinz-eugen', name: 'Prinz Eugen', nation: 'KMS', class: 'Admiral Hipper', type: 'Heavy Cruiser', hints: ['Neljä kaksoistykkitornia jakautuu kahteen keulassa ja kahteen perässä.', 'Yksi vino savupiippu ja korkea etuylärakenne hallitsevat aluksen keskiosaa.', 'Runko on kapeampi ja tykkitornit pienemmät kuin lähellä olevissa taistelulaivoissa.'], silhouette: 'Ships/KMS/Admiral%20Hipper/Prinz%20Eugen/Silhouette.jpg' },
  { id: 'kms-admiral-hipper', name: 'Admiral Hipper', nation: 'KMS', class: 'Admiral Hipper', type: 'Heavy Cruiser', hints: ['Neljä kaksoistykkitornia jakautuu kahteen keulassa ja kahteen perässä.', 'Yksi vino savupiippu ja korkea etuylärakenne hallitsevat aluksen keskiosaa.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama perusjärjestely.'], silhouette: 'Ships/KMS/Admiral%20Hipper/Admiral%20Hipper/Silhouette.jpg' }
];
