export const ships = [
  { id: 'hms-nelson', name: 'HMS Nelson', nation: 'HMS', class: 'Nelson', type: 'Battleship', hints: ['Kolme päätykkitornia on ryhmitetty kokonaan komentosillan etupuolelle.', 'Jokaisessa päätykkitornissa on kolme putkea: 3 + 3 + 3.', 'Etsi yksi savupiippu lyhyen ja tiiviin ylärakenteen takaa.'], silhouette: 'Ships/HMS/Nelson/HMS%20Nelson/Silhouette.png' },
  { id: 'hms-hood', name: 'HMS Hood', nation: 'HMS', class: 'Admiral', type: 'Battlecruiser', hints: ['Neljä kaksoistykkitornia jakautuu tasan: kaksi keulassa ja kaksi perässä.', 'Etsi kaksi näkyvää, lähellä toisiaan olevaa savupiippua keskilaivasta.', 'Pitkä ja matala runko saa aluksen näyttämään kokoonsa nähden hoikalta.'], silhouette: 'Ships/HMS/Admiral/HMS%20Hood/Silhouette.png' },
  { id: 'hms-king-george-v', name: 'HMS King George V', nation: 'HMS', class: 'King George V', type: 'Battleship', hints: ['Pääaseistus muodostuu kahdesta hyvin leveästä ja yhdestä kapeammasta tykkitornista.', 'Laske putket: 4 + 4 + 2; kaksi tornia keulassa ja yksi perässä.', 'Porrastettu etuylärakenne nousee heti keulan tykkitornien takaa.'], silhouette: 'Ships/HMS/King%20George%20V/HMS%20King%20George%20V/Silhouette.jpg' },
  { id: 'hms-prince-of-wales', name: 'HMS Prince of Wales', nation: 'HMS', class: 'King George V', type: 'Battleship', hints: ['Pääaseistus muodostuu kahdesta hyvin leveästä ja yhdestä kapeammasta tykkitornista.', 'Laske putket: 4 + 4 + 2; kaksi tornia keulassa ja yksi perässä.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama tykkijärjestely.'], silhouette: 'Ships/HMS/King%20George%20V/HMS%20Prince%20of%20Wales/Silhouette.jpg' },
  { id: 'hms-belfast', name: 'HMS Belfast', nation: 'HMS', class: 'Town', type: 'Light Cruiser', hints: ['Neljä kompaktia kolmoistykkitornia muodostaa parit keulaan ja perään.', 'Etsi kaksi hoikkaa, keskilaivan tuntumaan ryhmitettyä savupiippua.', 'Runko ja tykkitornit ovat selvästi kevyemmät ja pienemmät kuin taistelulaivassa.'], silhouette: 'Ships/HMS/Town/HMS%20Belfast/Silhouette.jpg' },
  { id: 'kms-bismarck', name: 'Bismarck', nation: 'KMS', class: 'Bismarck', type: 'Battleship', hints: ['Neljä kaksoistykkitornia on sijoitettu pareittain keulaan ja perään.', 'Yksi leveä savupiippu on korkean, porrastetun etutornin takana.', 'Korkea etuylärakenne on parempi tunnistuspiste kuin pelkkä tykkijärjestely.'], silhouette: 'Ships/KMS/Bismarck/Bismarck/Silhouette.jpg' },
  { id: 'kms-tirpitz', name: 'Tirpitz', nation: 'KMS', class: 'Bismarck', type: 'Battleship', hints: ['Neljä kaksoistykkitornia on sijoitettu pareittain keulaan ja perään.', 'Yksi leveä savupiippu on korkean, porrastetun etutornin takana.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama perusjärjestely.'], silhouette: 'Ships/KMS/Bismarck/Tirpitz/Silhouette.jpg' },
  { id: 'kms-scharnhorst', name: 'Scharnhorst', nation: 'KMS', class: 'Scharnhorst', type: 'Battleship', hints: ['Kolme kolmoistykkitornia muodostaa 2-keulassa, 1-perässä -järjestelyn.', 'Torneissa on yhteensä 3 + 3 + 3 putkea, ei neliputkisia torneja.', 'Etsi yksi leveä savupiippu ja verrattain virtaviivainen etutorni.'], silhouette: 'Ships/KMS/Scharnhorst/Scharnhorst/Silhouette.png' },
  { id: 'kms-gneisenau', name: 'Gneisenau', nation: 'KMS', class: 'Scharnhorst', type: 'Battleship', hints: ['Scharnhorst-luokan alus, jossa on kolme kolmoistykkitornia.', 'Pääaseistus on järjestetty kaksi tornia keulaan ja yksi perään.', 'Etsi korkea komentosilta, yksi savupiippu ja pitkä, virtaviivainen runko.'], silhouette: 'Ships/KMS/Scharnhorst/Gneisenau/Silhouette.svg' },
  { id: 'kms-prinz-eugen', name: 'Prinz Eugen', nation: 'KMS', class: 'Admiral Hipper', type: 'Heavy Cruiser', hints: ['Neljä kaksoistykkitornia jakautuu kahteen keulassa ja kahteen perässä.', 'Yksi vino savupiippu ja korkea etuylärakenne hallitsevat aluksen keskiosaa.', 'Runko on kapeampi ja tykkitornit pienemmät kuin lähellä olevissa taistelulaivoissa.'], silhouette: 'Ships/KMS/Admiral%20Hipper/Prinz%20Eugen/Silhouette.jpg' },
  { id: 'kms-admiral-hipper', name: 'Admiral Hipper', nation: 'KMS', class: 'Admiral Hipper', type: 'Heavy Cruiser', hints: ['Neljä kaksoistykkitornia jakautuu kahteen keulassa ja kahteen perässä.', 'Yksi vino savupiippu ja korkea etuylärakenne hallitsevat aluksen keskiosaa.', 'Tarkastele pieniä siluettieroja: aluksella on sisaralus, jolla on sama perusjärjestely.'], silhouette: 'Ships/KMS/Admiral%20Hipper/Admiral%20Hipper/Silhouette.jpg' }
,
  { id: 'hms-agincourt', name: 'HMS Agincourt', nation: 'HMS', class: 'Agincourt', type: 'Battleship', hints: ["Seitsemän päätykkitornia tekevät siluetista poikkeuksellisen tornirikkaan.","Pääaseistus on järjestetty pitkälle runkoon useana kaksoistykkitornina.","Pitkä, suhteellisen matala taistelulaivan runko ja tiheä torni­jono ovat hyviä tuntomerkkejä."], silhouette: 'Ships/HMS/Agincourt/HMS%20Agincourt/Silhouette.png' },
  { id: 'hms-ark-royal', name: 'HMS Ark Royal', nation: 'HMS', class: 'Ark Royal', type: 'Aircraft Carrier', hints: ["Pitkä, yhtenäinen lentokansi erottaa aluksen tykistöaluksista.","Suuri suorakaiteenomainen lentokansi hallitsee koko siluettia.","Saareke on sijoitettu lentokannen sivuun eikä keskelle alusta."], silhouette: 'Ships/HMS/Ark%20Royal/HMS%20Ark%20Royal/Silhouette.png' },
  { id: 'hms-courageous', name: 'HMS Courageous', nation: 'HMS', class: 'Courageous', type: 'Battlecruiser', hints: ["Alus tunnettiin alun perin suurena kevyenä taisteluristeilijänä.","Kaksi päätykkitornia edessä ja kaksi takana muodostavat tunnistettavan profiilin.","Pitkä ja suhteellisen hoikka runko on tyypillinen Courageous-luokalle."], silhouette: 'Ships/HMS/Courageous/HMS%20Courageous/Silhouette.png' },
  { id: 'hms-furious', name: 'HMS Furious', nation: 'HMS', class: 'Courageous', type: 'Battlecruiser', hints: ["Furious kuului samaan Courageous-luokkaan kuin HMS Courageous.","Sen lentotukialukseksi muuttunut rakenne erottaa sen sisaraluksen alkuperäisestä taisteluristeilijäprofiilista.","Pitkä lentokansi ja sivussa oleva saareke ovat tärkeimmät siluettimerkit."], silhouette: 'Ships/HMS/Courageous/HMS%20Furious/Silhouette.png' },
  { id: 'hms-erin', name: 'HMS Erin', nation: 'HMS', class: 'Erin', type: 'Battleship', hints: ["Kaksi päätykkitornia edessä ja kaksi perässä muodostavat selkeän neljän tornin profiilin.","Keskilaivan ylärakenne on kompakti ja savupiippu yksittäinen.","Erin oli suuri ensimmäisen maailmansodan aikakauden taistelulaiva."], silhouette: 'Ships/HMS/Erin/HMS%20Erin/Silhouette.png' },
  { id: 'hms-lion', name: 'HMS Lion', nation: 'HMS', class: 'Lion', type: 'Battlecruiser', hints: ["Lion on suuren brittiläisen taisteluristeilijän pitkä ja hoikka profiili.","Päätykkitornit ovat jakautuneet kahteen eteen ja kahteen taakse.","Korkea ylärakenne ja kaksi savupiippua auttavat erottamaan sen pienemmistä risteilijöistä."], silhouette: 'Ships/HMS/Lion/HMS%20Lion/Silhouette.png' },
  { id: 'hms-revenge', name: 'HMS Revenge', nation: 'HMS', class: 'Revenge', type: 'Battleship', hints: ["Viisi päätykkitornia muodostaa pitkän taistelulaivaprofiilin.","Kaksi tornia on keulassa, kaksi perässä ja yksi niiden välissä.","Matala ja raskas runko sekä useat kaksoistykkitornit ovat luokan hyviä tuntomerkkejä."], silhouette: 'Ships/HMS/Revenge/HMS%20Revenge/Silhouette.png' },
  { id: 'hms-tiger', name: 'HMS Tiger', nation: 'HMS', class: 'Tiger', type: 'Battlecruiser', hints: ["Tiger on pitkä ja virtaviivainen brittiläinen taisteluristeilijä.","Neljä kaksoistykkitornia on jaettu kahteen keulassa ja kahteen perässä.","Kaksi savupiippua ja pitkä runko antavat sille tunnistettavan siluetin."], silhouette: 'Ships/HMS/Tiger/HMS%20Tiger/Silhouette.png' },
  { id: 'hms-vanguard', name: 'HMS Vanguard', nation: 'HMS', class: 'Vanguard', type: 'Battleship', hints: ["Neljä kaksoistykkitornia jakautuu kahteen keulassa ja kahteen perässä.","Korkea komentosilta ja kaksi savupiippua hallitsevat keskilaivan profiilia.","Vanguard on erittäin suuri mutta siluetiltaan perinteinen brittiläinen taistelulaiva."], silhouette: 'Ships/HMS/Vanguard/HMS%20Vanguard/Silhouette.png' },
  { id: 'kms-roon', name: 'Roon', nation: 'KMS', class: 'Roon', type: 'Armoured Cruiser', hints: ["Roonilla on neljä kaksoistykkitornia, kaksi keulassa ja kaksi perässä.","Yksi savupiippu ja korkea keskilaivan ylärakenne ovat näkyviä tuntomerkkejä.","Se on saksalainen panssariristeilijä, joten sen runko on taistelulaivaa kevyempi."], silhouette: 'Ships/KMS/Roon/Roon/Silhouette.png' }
];
